-- MySQL Script generated by MySQL Workbench
-- sáb 29 ago 2020 17:22:22 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pruebamerqueo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pruebamerqueo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pruebamerqueo` ;
USE `pruebamerqueo` ;

-- -----------------------------------------------------
-- Table `pruebamerqueo`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebamerqueo`.`inventory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` VARCHAR(45) NOT NULL,
  `quantity` TINYINT(10) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_id_index` (`product_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebamerqueo`.`order_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebamerqueo`.`order_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` VARCHAR(45) NOT NULL,
  `order_id` VARCHAR(45) NOT NULL,
  `quantity` TINYINT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_id_index` (`product_id` ASC) VISIBLE,
  INDEX `order_id_index` (`order_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebamerqueo`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebamerqueo`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NOT NULL,
  `priority` TINYINT(1) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `delivery_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_index` (`user_id` ASC) VISIBLE,
  INDEX `delivery_date_index` (`delivery_date` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebamerqueo`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebamerqueo`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebamerqueo`.`provider_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebamerqueo`.`provider_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `provider_id` VARCHAR(45) NOT NULL,
  `product_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `provider_id_index` (`provider_id` ASC) VISIBLE,
  INDEX `product_id_index` (`product_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebamerqueo`.`providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebamerqueo`.`providers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebamerqueo`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pruebamerqueo`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
